# Generated by Django 6.0.2 on 2026-02-10 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('section', models.CharField(choices=[('Bath', 'Bath'), ('Kitchen', 'Kitchen')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('section', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(10000.0, 'Price must be less than 10000!'), django.core.validators.MinValueValidator(0.0, 'Price must be greater than zero!')])),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_promo', models.BooleanField(default=False)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
