# Generated by Django 6.0.2 on 2026-02-10 20:28

import core.validators.validate_file_size_15mb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_section_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[core.validators.validate_file_size_15mb.validate_file_size_15mb]),
        ),
    ]
